### ISSUE TITLE
2cc issues on specific vehicles

### ISSUE THREAD

**Issue by BL97** [citymania-org/robs-trains#17]
2cc issues on specific vehicles
![image](https://github.com/user-attachments/assets/279f1513-817e-41a5-8167-d83a62dc640d)
![image](https://github.com/user-attachments/assets/6e4f50a7-67f8-4cef-a811-1d024b308762)
![image](https://github.com/user-attachments/assets/cae97e90-f948-4a75-a398-6608b31945d1)
![image](https://github.com/user-attachments/assets/c7c6fe34-1549-44a4-93ca-fde6db027717)
image 1 & 2 show that 2cc doesnt work properly on the swedish C stock however 3 & 4 show that it does work on other vehicles, we couldnt figure out the issue

**Comment by Brickblock1** [comment]
I have found the issue

**Comment by Brickblock1** [comment]
grf-py automatically adds flags from the front most vehicle when adding length > 8 parts but for parts of length < 8 this doesn't happen.
